import { FormGroup, FormControl } from "@angular/forms";
export declare class ValidationManager {
    private inputsRaw;
    private displayError;
    private controls;
    formGroup: FormGroup;
    formControls: {};
    errors: {};
    submitted: boolean;
    constructor(inputsRaw: any, displayError?: string[]);
    getForm(): FormGroup;
    isValid(): boolean;
    hasError(field: any): boolean;
    getError(field: any): any;
    setError(field: any, message: any): void;
    getErrors(): {};
    reset(): void;
    onValueChanged(displayError?: any): void;
    setValue(values: any, value?: any): void;
    getValue(controlKey: string): any;
    buildControl(name: any, rules: any): {
        control: FormControl;
        messages: {};
    };
    private getErrorMessage(field, rule);
    private buildMessage(name, rule, arg?);
    getMessage(rule: any): any;
}
export declare const VALIDATION_MESSAGES: {
    'required': string;
    'requiredwith': string;
    'minlength': string;
    'maxlength': string;
    'alpha': string;
    'alphaspace': string;
    'alphanum': string;
    'alphanumspace': string;
    'url': string;
    'number': string;
    'digits': string;
    'creditcard': string;
    'range': string;
    'rangelength': string;
    'max': string;
    'min': string;
    'email': string;
    'date': string;
    'mindate': string;
    'maxdate': string;
    'dateiso': string;
    'equal': string;
    'equalto': string;
    'json': string;
};
